//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComandaDetalle
    {
        public int Id { get; set; }
        public int ComandaID { get; set; }
        public int ProductoID { get; set; }
        public double Precio { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Comanda Comanda { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
